# Generated by Django 5.1.1 on 2025-04-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='member',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberInfo',
        ),
    ]
