# Generated by Django 5.1.1 on 2025-04-26 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('login', '0002_remove_member_category_remove_subscription_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='dashboard.category'),
        ),
    ]
